apiVersion: v1
kind: Service
metadata:
  name: es-nginx-nodeport
spec:
  ports:
  - name: http
    nodePort: 30246
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    workload.user.cattle.io/workloadselector: deployment-es-cluster-es-nginx
  type: NodePort