apiVersion: v1
data:
  nginx.conf: |-
    worker_processes  2;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;
    events {
        worker_connections  4096;  ## Default: 1024
    }

    http {
        client_max_body_size 10m;
        server { # simple reverse-proxy
            listen 80;
            location / {
              proxy_pass  http://es01:9200;
            }
        }
    }
kind: ConfigMap
metadata:
  name: es-nginx