apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-es-cluster-es01
  name: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-es-cluster-es01
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-es-cluster-es01
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: cluster.initial_master_nodes
          value: es01
        - name: cluster.name
          value: sr-es-cluster
        - name: http.cors.allow-origin
          value: '*'
        - name: http.cors.enabled
          value: "true"
        - name: node.name
          value: es01
        image: elasticsearch:5.6
        imagePullPolicy: IfNotPresent
        name: es01
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox:1.27.2
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        securityContext:
          privileged: true
      restartPolicy: Always