apiVersion: v1
kind: Service
metadata:
  name: es01
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: http
  selector:
    workload.user.cattle.io/workloadselector: deployment-es-cluster-es01
  type: ClusterIP
status:
  loadBalancer: {}
