apiVersion: v1
kind: Service
metadata:
  name: es02
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: http
  selector:
    workload.user.cattle.io/workloadselector: deployment-es-cluster-es02
  type: ClusterIP
