apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
spec:
  ports:
  - name: 5601tcp01
    nodePort: 30245
    port: 5601
    protocol: TCP
    targetPort: 5601tcp01
  selector:
    workload.user.cattle.io/workloadselector: deployment-es-cluster-kibana
  type: NodePort